ALTER TABLE "ShopItem" ADD COLUMN "emoji" TEXT NOT NULL DEFAULT '📦';
ALTER TABLE "ShopItem" ADD COLUMN "usageType" TEXT NOT NULL DEFAULT 'consume';
ALTER TABLE "ShopItem" ADD COLUMN "usageCount" INTEGER;
ALTER TABLE "ShopItem" ADD COLUMN "imageUrl" TEXT;
